<?php

/**
 * Implements hook_entity_insert().
 */
function islandora_pid_alias_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  // @todo: Make the entity types configurable.
  if ($entity->getType() == 'islandora_object') {
    if ($entity->hasField('field_pid')) {
      $pid_value = $entity->get('field_pid')->getValue();
      $pid = $pid_value[0]['value'];
      if (strlen($pid)) {
        $path = \Drupal::service('path.alias_storage')->save("/node/" . $entity->id(), "/object/" . $pid, "en");
      }
    }
  }
}
